### ISSUE TITLE
Application stops after 3 hours

### ISSUE THREAD

**Issue by keptenkurk** [keptenkurk/pyTTNmap#7]
Was able to catch the error:
`
b'$GPGGA,033447.00,5133.50513,N,00533.57670,E,1,06,1.63,24.1,M,46.2,M,,*6B\r\n'
Longitude (5, 33.5767, 'E')
Latitude (51, 33.50513, 'N')
UTC Timestamp: (3, 34, 47.0)
Fix Status: 1
Altitude: 24.1
Horizontal Dilution of Precision: 1.63
Satellites in Use by Receiver: 6
b'\x06\x8c\x01\x00\x0e'
b'$GPGGA,033449.00,,,,,0,05,7.66,,,,,,*5D\r\n'
Longitude (5, 33.5767, 'E')
Latitude (51, 33.50513, 'N')
UTC Timestamp: (3, 34, 49.0)
Fix Status: 0
Altitude: 24.1
Horizontal Dilution of Precision: 7.66
Satellites in Use by Receiver: 5
Traceback (most recent call last):
  File "main.py", line 83, in <module>
  File "gps_data.py", line 53, in get_loc
NameError: local variable referenced before assignment
MicroPython v1.8.6-849-d0dc708 on 2018-02-27; LoPy with ESP32
Type "help()" for more information.
>>>
`

**Comment by keptenkurk** [comment]
Note that GPS just lost fix before the error. At that time timestamp is not yet initialized. Should only occur at the moment of loosing fix... 
Fixed (?) in 6c31c975151ce240e57db4e691ef56fa9a4df478

**Comment by keptenkurk** [comment]
Not seen again.
